---

service: resume-website
provider:
  stage: ${opt:stage, 'prod'}
  name: aws
  region: eu-west-1
  role: ${'arn:aws:iam::782412278538:role/service-role/flask_website_contact-role-qojehzjn'}
  runtime: python3.7

package:
  individually: true
  exclude:
    - ./**

functions:
  contact:
    handler: contact.handler
    package:
      include:
        - contact.py
    environment:
      SNS_TOPIC: ${env:SNS_TOPIC, ''}